import { HomeScreen as ActualHomeScreen } from "./HomeScreen";
import { FindMatchScreen } from "./FindMatchScreen";
import { MessagesScreen as ActualMessagesScreen } from "./MessagesScreen";
import { ProfileScreen as ActualProfileScreen } from "./ProfileScreen";
import { CreateMatchScreen as ActualCreateMatchScreen } from "./CreateMatchScreen";
import { MatchDetailScreen as ActualMatchDetailScreen } from "./MatchDetailScreen";
import { CompetitionsScreen as ActualCompetitionsScreen } from "./CompetitionsScreen";
import { CompetitionDetailScreen as ActualCompetitionDetailScreen } from "./CompetitionDetailScreen";
import { ConversationViewScreen as ActualConversationViewScreen } from "./ConversationViewScreen";
import { NotificationsScreen as ActualNotificationsScreen } from "./NotificationsScreen";
import { EditProfileScreen as ActualEditProfileScreen } from "./EditProfileScreen";
import { PlayersScreen as ActualPlayersScreen } from "./PlayersScreen";
import { FriendsScreen as ActualFriendsScreen } from "./FriendsScreen";
import { PlayerProfileScreen as ActualPlayerProfileScreen } from "./PlayerProfileScreen";
import { CreateCompetitionScreen as ActualCreateCompetitionScreen } from "./CreateCompetitionScreen";
import { MatchChatScreen as ActualMatchChatScreen } from "./MatchChatScreen";
import { InstantPlayScreen as ActualInstantPlayScreen } from "./InstantPlayScreen";
import { PastEventsScreen as ActualPastEventsScreen } from "./PastEventsScreen";
import { AcceptInviteScreen as ActualAcceptInviteScreen } from "./AcceptInviteScreen";
import { VerificationScreen as ActualVerificationScreen } from "./VerificationScreen";
import { InvitePlayersScreen as ActualInvitePlayersScreen } from "./InvitePlayersScreen";
import { OnboardingScreen as ActualOnboardingScreen } from "./OnboardingScreen";

export const HomeScreen = ActualHomeScreen;
export const DiscoverScreen = FindMatchScreen;
export const MessagesScreen = ActualMessagesScreen;
export const ProfileScreen = ActualProfileScreen;

export const CreateMatchScreen = ActualCreateMatchScreen;
export const MatchDetailScreen = ActualMatchDetailScreen;
export const EditProfileScreen = ActualEditProfileScreen;
export const NotificationsScreen = ActualNotificationsScreen;
export const CompetitionsScreen = ActualCompetitionsScreen;
export const CreateCompetitionScreen = ActualCreateCompetitionScreen;
export const CompetitionDetailScreen = ActualCompetitionDetailScreen;
export const InvitePlayersScreen = ActualInvitePlayersScreen;
export const VerificationScreen = ActualVerificationScreen;
export const InstantPlayScreen = ActualInstantPlayScreen;
export const PlayersScreen = ActualPlayersScreen;
export const PlayerProfileScreen = ActualPlayerProfileScreen;
export const FriendsScreen = ActualFriendsScreen;
export const PastEventsScreen = ActualPastEventsScreen;
export const ConversationViewScreen = ActualConversationViewScreen;
export const MatchChatScreen = ActualMatchChatScreen;
export const AcceptInviteScreen = ActualAcceptInviteScreen;
export const OnboardingScreen = ActualOnboardingScreen;
