import React from "react";
import { PlaceholderScreen } from "./PlaceholderScreen";
import { HomeScreen as ActualHomeScreen } from "./HomeScreen";
import { FindMatchScreen } from "./FindMatchScreen";
import { MessagesScreen as ActualMessagesScreen } from "./MessagesScreen";
import { ProfileScreen as ActualProfileScreen } from "./ProfileScreen";
import { CreateMatchScreen as ActualCreateMatchScreen } from "./CreateMatchScreen";
import { MatchDetailScreen as ActualMatchDetailScreen } from "./MatchDetailScreen";
import { CompetitionsScreen as ActualCompetitionsScreen } from "./CompetitionsScreen";
import { CompetitionDetailScreen as ActualCompetitionDetailScreen } from "./CompetitionDetailScreen";
import { ConversationViewScreen as ActualConversationViewScreen } from "./ConversationViewScreen";
import { NotificationsScreen as ActualNotificationsScreen } from "./NotificationsScreen";
import { EditProfileScreen as ActualEditProfileScreen } from "./EditProfileScreen";
import { PlayersScreen as ActualPlayersScreen } from "./PlayersScreen";
import { FriendsScreen as ActualFriendsScreen } from "./FriendsScreen";

export const HomeScreen = ActualHomeScreen;
export const DiscoverScreen = FindMatchScreen;
export const MessagesScreen = ActualMessagesScreen;
export const ProfileScreen = ActualProfileScreen;

export const CreateMatchScreen = ActualCreateMatchScreen;
export const MatchDetailScreen = ActualMatchDetailScreen;
export const EditProfileScreen = ActualEditProfileScreen;
export const NotificationsScreen = ActualNotificationsScreen;
export const CompetitionsScreen = ActualCompetitionsScreen;
export const CreateCompetitionScreen = () => <PlaceholderScreen title="Create Competition" />;
export const CompetitionDetailScreen = ActualCompetitionDetailScreen;
export const InvitePlayersScreen = () => <PlaceholderScreen title="Invite Players" />;
export const VerificationScreen = () => <PlaceholderScreen title="Verification" />;
export const InstantPlayScreen = () => <PlaceholderScreen title="Instant Play" />;
export const PlayersScreen = ActualPlayersScreen;
export const PlayerProfileScreen = () => <PlaceholderScreen title="Player Profile" />;
export const FriendsScreen = ActualFriendsScreen;
export const PastEventsScreen = () => <PlaceholderScreen title="Past Events" />;
export const ConversationViewScreen = ActualConversationViewScreen;
export const MatchChatScreen = () => <PlaceholderScreen title="Match Chat" />;
export const AcceptInviteScreen = () => <PlaceholderScreen title="Accept Invite" />;
export const OnboardingScreen = () => <PlaceholderScreen title="Onboarding" subtitle="Profile setup and preferences" />;
