import React from "react";
import { PlaceholderScreen } from "./PlaceholderScreen";
import { HomeScreen as ActualHomeScreen } from "./HomeScreen";
import { FindMatchScreen } from "./FindMatchScreen";
import { MessagesScreen as ActualMessagesScreen } from "./MessagesScreen";
import { ProfileScreen as ActualProfileScreen } from "./ProfileScreen";
import { CreateMatchScreen as ActualCreateMatchScreen } from "./CreateMatchScreen";
import { MatchDetailScreen as ActualMatchDetailScreen } from "./MatchDetailScreen";

export const HomeScreen = ActualHomeScreen;
export const DiscoverScreen = FindMatchScreen;
export const MessagesScreen = ActualMessagesScreen;
export const ProfileScreen = ActualProfileScreen;

export const CreateMatchScreen = ActualCreateMatchScreen;
export const MatchDetailScreen = ActualMatchDetailScreen;
export const EditProfileScreen = () => <PlaceholderScreen title="Edit Profile" />;
export const NotificationsScreen = () => <PlaceholderScreen title="Notifications" />;
export const CompetitionsScreen = () => <PlaceholderScreen title="Competitions" />;
export const CreateCompetitionScreen = () => <PlaceholderScreen title="Create Competition" />;
export const CompetitionDetailScreen = () => <PlaceholderScreen title="Competition Detail" />;
export const InvitePlayersScreen = () => <PlaceholderScreen title="Invite Players" />;
export const VerificationScreen = () => <PlaceholderScreen title="Verification" />;
export const InstantPlayScreen = () => <PlaceholderScreen title="Instant Play" />;
export const PlayersScreen = () => <PlaceholderScreen title="Players" />;
export const PlayerProfileScreen = () => <PlaceholderScreen title="Player Profile" />;
export const FriendsScreen = () => <PlaceholderScreen title="Friends" />;
export const PastEventsScreen = () => <PlaceholderScreen title="Past Events" />;
export const ConversationViewScreen = () => <PlaceholderScreen title="Conversation" />;
export const MatchChatScreen = () => <PlaceholderScreen title="Match Chat" />;
export const AcceptInviteScreen = () => <PlaceholderScreen title="Accept Invite" />;
export const OnboardingScreen = () => <PlaceholderScreen title="Onboarding" subtitle="Profile setup and preferences" />;
